# Generated by Django 5.2.4 on 2025-08-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_admin_options_seller_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='seller',
            name='shop_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterModelTable(
            name='admin',
            table='main_admin',
        ),
    ]
