# Generated by Django 5.1.7 on 2025-08-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_seller_name_alter_seller_shop_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewCategory',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
