# Generated by Django 5.2.4 on 2026-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_cancelled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
