# Generated by Django 5.1.7 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_refundproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='refunds/'),
        ),
        migrations.AddField(
            model_name='refund',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
