# Generated by Django 5.1.7 on 2026-04-13 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_refund_payment_screenshot_refund_rejection_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='rejection_reason',
        ),
    ]
