# Generated by Django 5.1.7 on 2026-04-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_refund_payment_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_image',
            field=models.ImageField(blank=True, null=True, upload_to='refunds/'),
        ),
        migrations.AddField(
            model_name='refund',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
