# Generated by Django 5.1.7 on 2026-04-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_refund_refund_image_refund_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='address_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('refund requested', 'Refund Requested')], default='pending', max_length=100),
        ),
    ]
