# Generated by Django 5.1.7 on 2026-05-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_message_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
