# Generated by Django 5.1.7 on 2026-05-02 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_commissionsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
    ]
