# Generated by Django 5.1.7 on 2026-05-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_sitesetting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('customer', 'seller')},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='product',
        ),
    ]
